//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Website {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Website.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string APPLICATON {
            get {
                return ResourceManager.GetString("APPLICATON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string APPLY {
            get {
                return ResourceManager.GetString("APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string CONTACTUS {
            get {
                return ResourceManager.GetString("CONTACTUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our business hours are:.
        /// </summary>
        public static string CONTACTUS_HOURS_DESC {
            get {
                return ResourceManager.GetString("CONTACTUS_HOURS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Hours.
        /// </summary>
        public static string CONTACTUS_HOURS_HEAD {
            get {
                return ResourceManager.GetString("CONTACTUS_HOURS_HEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call or text us at: .
        /// </summary>
        public static string CONTACTUS_INFO_DESC1 {
            get {
                return ResourceManager.GetString("CONTACTUS_INFO_DESC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email us at: .
        /// </summary>
        public static string CONTACTUS_INFO_DESC2 {
            get {
                return ResourceManager.GetString("CONTACTUS_INFO_DESC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our mailing address is: .
        /// </summary>
        public static string CONTACTUS_INFO_DESC3 {
            get {
                return ResourceManager.GetString("CONTACTUS_INFO_DESC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string CONTACTUS_INFO_HEAD {
            get {
                return ResourceManager.GetString("CONTACTUS_INFO_HEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration reloaded successfully.
        /// </summary>
        public static string HOME_CONFIG_RELOADED {
            get {
                return ResourceManager.GetString("HOME_CONFIG_RELOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill our online application from your computer or mobile device.
        /// </summary>
        public static string INDEX_APPLY_DESC {
            get {
                return ResourceManager.GetString("INDEX_APPLY_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply now.
        /// </summary>
        public static string INDEX_APPLY_LINK {
            get {
                return ResourceManager.GetString("INDEX_APPLY_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply offline.
        /// </summary>
        public static string INDEX_APPLY_OFFLINE_LINK {
            get {
                return ResourceManager.GetString("INDEX_APPLY_OFFLINE_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email, call, or text us with any questions. We are happy to help!.
        /// </summary>
        public static string INDEX_CONTACTUS_DESC {
            get {
                return ResourceManager.GetString("INDEX_CONTACTUS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View contact info.
        /// </summary>
        public static string INDEX_CONTACTUS_LINK {
            get {
                return ResourceManager.GetString("INDEX_CONTACTUS_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committed to providing quality housing for quality people..
        /// </summary>
        public static string INDEX_JUMBO_DESC {
            get {
                return ResourceManager.GetString("INDEX_JUMBO_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find information about utilities, maintenance requests, and other services..
        /// </summary>
        public static string INDEX_TENANTINFO_DESC {
            get {
                return ResourceManager.GetString("INDEX_TENANTINFO_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View tenant info.
        /// </summary>
        public static string INDEX_TENANTINFO_LINK {
            get {
                return ResourceManager.GetString("INDEX_TENANTINFO_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Request.
        /// </summary>
        public static string MAINTENANCE_REQUEST {
            get {
                return ResourceManager.GetString("MAINTENANCE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact info.
        /// </summary>
        public static string MAINTENANCE_REQUEST_CONTACT_INFO {
            get {
                return ResourceManager.GetString("MAINTENANCE_REQUEST_CONTACT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit maintenance request online.
        /// </summary>
        public static string MAINTENANCE_REQUEST_SUBMIT_ONLINE {
            get {
                return ResourceManager.GetString("MAINTENANCE_REQUEST_SUBMIT_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please resolve the following errors.
        /// </summary>
        public static string RESOLVE_ERRORS {
            get {
                return ResourceManager.GetString("RESOLVE_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Info.
        /// </summary>
        public static string TENANTINFO {
            get {
                return ResourceManager.GetString("TENANTINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City of Bozeman.
        /// </summary>
        public static string TENANTINFO_CITYOFBZN {
            get {
                return ResourceManager.GetString("TENANTINFO_CITYOFBZN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloadable PDF Documents.
        /// </summary>
        public static string TENANTINFO_DOCS {
            get {
                return ResourceManager.GetString("TENANTINFO_DOCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical.
        /// </summary>
        public static string TENANTINFO_ELECTRICAL {
            get {
                return ResourceManager.GetString("TENANTINFO_ELECTRICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.
        /// </summary>
        public static string TENANTINFO_GAS {
            get {
                return ResourceManager.GetString("TENANTINFO_GAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone / TV / Internet.
        /// </summary>
        public static string TENANTINFO_INTERNET {
            get {
                return ResourceManager.GetString("TENANTINFO_INTERNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string TENANTINFO_MAINTENANCE {
            get {
                return ResourceManager.GetString("TENANTINFO_MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newspaper.
        /// </summary>
        public static string TENANTINFO_NEWSPAPER {
            get {
                return ResourceManager.GetString("TENANTINFO_NEWSPAPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Office.
        /// </summary>
        public static string TENANTINFO_POSTOFFICE {
            get {
                return ResourceManager.GetString("TENANTINFO_POSTOFFICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string TENANTINFO_SERVICES {
            get {
                return ResourceManager.GetString("TENANTINFO_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        public static string TENANTINFO_TRASH {
            get {
                return ResourceManager.GetString("TENANTINFO_TRASH", resourceCulture);
            }
        }
    }
}
