//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Website {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Logs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Website.Logs", typeof(Logs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking model.
        /// </summary>
        public static string checkingModel {
            get {
                return ResourceManager.GetString("checkingModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting HTML to PDF.
        /// </summary>
        public static string convertingHtmlToPDF {
            get {
                return ResourceManager.GetString("convertingHtmlToPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating HTML string for razor view.
        /// </summary>
        public static string creatingViewHtml {
            get {
                return ResourceManager.GetString("creatingViewHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get service configuration.
        /// </summary>
        public static string failGetSvcConfig {
            get {
                return ResourceManager.GetString("failGetSvcConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set log level from service configuration.
        /// </summary>
        public static string failSetLogLevel {
            get {
                return ResourceManager.GetString("failSetLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create and send submitted application.
        /// </summary>
        public static string failSubmitApp {
            get {
                return ResourceManager.GetString("failSubmitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create and send maintenance request.
        /// </summary>
        public static string failSubmitMaintReq {
            get {
                return ResourceManager.GetString("failSubmitMaintReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished sending application in email.
        /// </summary>
        public static string finishedSendingEmail {
            get {
                return ResourceManager.GetString("finishedSendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished sending maintanence request in email.
        /// </summary>
        public static string finishedSendingMaintEmail {
            get {
                return ResourceManager.GetString("finishedSendingMaintEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending application in email.
        /// </summary>
        public static string sendingEmail {
            get {
                return ResourceManager.GetString("sendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending maintanence request in email.
        /// </summary>
        public static string sendingMaintEmail {
            get {
                return ResourceManager.GetString("sendingMaintEmail", resourceCulture);
            }
        }
    }
}
