//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corely.DocuWareService.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedAndConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedAndConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Corely.DocuWareService.Resources.SharedAndConfig", typeof(SharedAndConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key is invalid.
        /// </summary>
        internal static string apiKeyInvalid {
            get {
                return ResourceManager.GetString("apiKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key is not set.
        /// </summary>
        internal static string apiKeyNotSet {
            get {
                return ResourceManager.GetString("apiKeyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection not found for guid.
        /// </summary>
        internal static string connNotFoundForId {
            get {
                return ResourceManager.GetString("connNotFoundForId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create new connection.
        /// </summary>
        internal static string failCreateConnection {
            get {
                return ResourceManager.GetString("failCreateConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get DW credentials.
        /// </summary>
        internal static string failGetDWCredentials {
            get {
                return ResourceManager.GetString("failGetDWCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get DW credentials list.
        /// </summary>
        internal static string failGetDWCredentialsList {
            get {
                return ResourceManager.GetString("failGetDWCredentialsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get service configuration.
        /// </summary>
        internal static string failGetSvcConfig {
            get {
                return ResourceManager.GetString("failGetSvcConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reload service configuration.
        /// </summary>
        internal static string failReloadServiceConfig {
            get {
                return ResourceManager.GetString("failReloadServiceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set DW credentials.
        /// </summary>
        internal static string failSetDWCredentials {
            get {
                return ResourceManager.GetString("failSetDWCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set log level from service configuration.
        /// </summary>
        internal static string failSetLogLevel {
            get {
                return ResourceManager.GetString("failSetLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to test DocuWare connection.
        /// </summary>
        internal static string failTestConnection {
            get {
                return ResourceManager.GetString("failTestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update password.
        /// </summary>
        internal static string failUpdatePW {
            get {
                return ResourceManager.GetString("failUpdatePW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml string was invalid (couldn&apos;t deserialize to credentials object).
        /// </summary>
        internal static string invalidXml {
            get {
                return ResourceManager.GetString("invalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WcfServiceLog.
        /// </summary>
        internal static string logFileName {
            get {
                return ResourceManager.GetString("logFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password provided does not matched stored password.
        /// </summary>
        internal static string oldPasswordWrong {
            get {
                return ResourceManager.GetString("oldPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters cannot be empty.
        /// </summary>
        internal static string paramsNotEmpty {
            get {
                return ResourceManager.GetString("paramsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password do not match.
        /// </summary>
        internal static string passwordsDontMatch {
            get {
                return ResourceManager.GetString("passwordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated successfully.
        /// </summary>
        internal static string passwordUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("passwordUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF Service.
        /// </summary>
        internal static string serviceName {
            get {
                return ResourceManager.GetString("serviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service credentials not found.
        /// </summary>
        internal static string svcCredentialsNotFound {
            get {
                return ResourceManager.GetString("svcCredentialsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;update&apos; parameter must be set to &apos;svc&apos; or a guid.
        /// </summary>
        internal static string updateParamWrong {
            get {
                return ResourceManager.GetString("updateParamWrong", resourceCulture);
            }
        }
    }
}
