//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corely.FlexiCapture.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LineSplitSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LineSplitSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Corely.FlexiCapture.Resources.LineSplitSettings", typeof(LineSplitSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot be empty.
        /// </summary>
        internal static string cannotBeEmpy {
            get {
                return ResourceManager.GetString("cannotBeEmpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string line {
            get {
                return ResourceManager.GetString("line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must have one entry.
        /// </summary>
        internal static string mustHaveOne {
            get {
                return ResourceManager.GetString("mustHaveOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No invoice lines marked for splitting.
        /// </summary>
        internal static string noInvoicesMarked {
            get {
                return ResourceManager.GetString("noInvoicesMarked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No distrubtion settings selected.
        /// </summary>
        internal static string noSettingsSelected {
            get {
                return ResourceManager.GetString("noSettingsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter not set.
        /// </summary>
        internal static string paramNoSet {
            get {
                return ResourceManager.GetString("paramNoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitting row.
        /// </summary>
        internal static string prog_splittingRow {
            get {
                return ResourceManager.GetString("prog_splittingRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to property error.
        /// </summary>
        internal static string propertyError {
            get {
                return ResourceManager.GetString("propertyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split settings selection failed.
        /// </summary>
        internal static string settingsSelectionFailed {
            get {
                return ResourceManager.GetString("settingsSelectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitting cancelled by user.
        /// </summary>
        internal static string splitCancelledByUser {
            get {
                return ResourceManager.GetString("splitCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line split failed with exception.
        /// </summary>
        internal static string splitFailed {
            get {
                return ResourceManager.GetString("splitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split succeeded.
        /// </summary>
        internal static string splitSucceeded {
            get {
                return ResourceManager.GetString("splitSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitting cancelled.
        /// </summary>
        internal static string splittingCancelled {
            get {
                return ResourceManager.GetString("splittingCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value must be in range.
        /// </summary>
        internal static string valueInRange {
            get {
                return ResourceManager.GetString("valueInRange", resourceCulture);
            }
        }
    }
}
