//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.BusinessLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.BusinessLayer.ApplicationValidation", typeof(ApplicationValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Required.
        /// </summary>
        public static string ADDRESS_CITY {
            get {
                return ResourceManager.GetString("ADDRESS_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Required.
        /// </summary>
        public static string ADDRESS_STATE {
            get {
                return ResourceManager.GetString("ADDRESS_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Required.
        /// </summary>
        public static string ADDRESS_STREET {
            get {
                return ResourceManager.GetString("ADDRESS_STREET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Required.
        /// </summary>
        public static string ADDRESS_ZIP {
            get {
                return ResourceManager.GetString("ADDRESS_ZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_ACCOMMODATION {
            get {
                return ResourceManager.GetString("APP_ACCOMMODATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Required.
        /// </summary>
        public static string APP_ACCOMMODATION_DESCRIBE {
            get {
                return ResourceManager.GetString("APP_ACCOMMODATION_DESCRIBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add personal reference.
        /// </summary>
        public static string APP_ADD_PERSONAL_REF {
            get {
                return ResourceManager.GetString("APP_ADD_PERSONAL_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another reference.
        /// </summary>
        public static string APP_ADD_RENT_REF {
            get {
                return ResourceManager.GetString("APP_ADD_RENT_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_ANTICIPATED_DURATION {
            get {
                return ResourceManager.GetString("APP_ANTICIPATED_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_ATTEND_COLLEGE {
            get {
                return ResourceManager.GetString("APP_ATTEND_COLLEGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Required.
        /// </summary>
        public static string APP_AUTOMOBILE {
            get {
                return ResourceManager.GetString("APP_AUTOMOBILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_CERT_AND_AUTH {
            get {
                return ResourceManager.GetString("APP_CERT_AND_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduation Date Required.
        /// </summary>
        public static string APP_COLLEGE_GRADUATE {
            get {
                return ResourceManager.GetString("APP_COLLEGE_GRADUATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years Attended Required.
        /// </summary>
        public static string APP_COLLEGE_YEARS {
            get {
                return ResourceManager.GetString("APP_COLLEGE_YEARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_CONSIDER_OTHER_INCOME {
            get {
                return ResourceManager.GetString("APP_CONSIDER_OTHER_INCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation Required.
        /// </summary>
        public static string APP_CRIMINAL_RECORD {
            get {
                return ResourceManager.GetString("APP_CRIMINAL_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_DRINKERS {
            get {
                return ResourceManager.GetString("APP_DRINKERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_DRINKERS_COUNT {
            get {
                return ResourceManager.GetString("APP_DRINKERS_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_DRINKERS_HOWOFTEN {
            get {
                return ResourceManager.GetString("APP_DRINKERS_HOWOFTEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation Required.
        /// </summary>
        public static string APP_EVICTED_EXPLAIN {
            get {
                return ResourceManager.GetString("APP_EVICTED_EXPLAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_HAS_AUTO {
            get {
                return ResourceManager.GetString("APP_HAS_AUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_HAS_BEEN_EVICTED {
            get {
                return ResourceManager.GetString("APP_HAS_BEEN_EVICTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_HAS_CRIMINAL_RECORD {
            get {
                return ResourceManager.GetString("APP_HAS_CRIMINAL_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_HAS_SECOND_JOB {
            get {
                return ResourceManager.GetString("APP_HAS_SECOND_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_MARIJUANA {
            get {
                return ResourceManager.GetString("APP_MARIJUANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_NON_HUMAN {
            get {
                return ResourceManager.GetString("APP_NON_HUMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Required.
        /// </summary>
        public static string APP_NON_HUMAN_DESCRIBE {
            get {
                return ResourceManager.GetString("APP_NON_HUMAN_DESCRIBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_OTHER_APPLICANTS {
            get {
                return ResourceManager.GetString("APP_OTHER_APPLICANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation Required.
        /// </summary>
        public static string APP_OTHER_INCOME {
            get {
                return ResourceManager.GetString("APP_OTHER_INCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_PARENTS_PAY {
            get {
                return ResourceManager.GetString("APP_PARENTS_PAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_PETS {
            get {
                return ResourceManager.GetString("APP_PETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Required.
        /// </summary>
        public static string APP_PETS_DESCRIBE {
            get {
                return ResourceManager.GetString("APP_PETS_DESCRIBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental Reference #2.
        /// </summary>
        public static string APP_RENT_REF_1 {
            get {
                return ResourceManager.GetString("APP_RENT_REF_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental Reference #3.
        /// </summary>
        public static string APP_RENT_REF_2 {
            get {
                return ResourceManager.GetString("APP_RENT_REF_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_RENTAL_ADDRESS {
            get {
                return ResourceManager.GetString("APP_RENTAL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_SMOKERS {
            get {
                return ResourceManager.GetString("APP_SMOKERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string APP_SMOKERS_COUNT {
            get {
                return ResourceManager.GetString("APP_SMOKERS_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Required.
        /// </summary>
        public static string AUTO_COLOR {
            get {
                return ResourceManager.GetString("AUTO_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate # Required.
        /// </summary>
        public static string AUTO_LICENSE_NUM {
            get {
                return ResourceManager.GetString("AUTO_LICENSE_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Required.
        /// </summary>
        public static string AUTO_MAKE {
            get {
                return ResourceManager.GetString("AUTO_MAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Required.
        /// </summary>
        public static string AUTO_MODEL {
            get {
                return ResourceManager.GetString("AUTO_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Required.
        /// </summary>
        public static string AUTO_STATE {
            get {
                return ResourceManager.GetString("AUTO_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Required.
        /// </summary>
        public static string AUTO_YEAR {
            get {
                return ResourceManager.GetString("AUTO_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Required.
        /// </summary>
        public static string EMPLOY_COMPANY {
            get {
                return ResourceManager.GetString("EMPLOY_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Required.
        /// </summary>
        public static string EMPLOY_CONTACT {
            get {
                return ResourceManager.GetString("EMPLOY_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Required.
        /// </summary>
        public static string EMPLOY_HOURS {
            get {
                return ResourceManager.GetString("EMPLOY_HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string EMPLOY_LENGTH {
            get {
                return ResourceManager.GetString("EMPLOY_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string EMPLOY_PERMENANT {
            get {
                return ResourceManager.GetString("EMPLOY_PERMENANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone # Required.
        /// </summary>
        public static string EMPLOY_PHONE {
            get {
                return ResourceManager.GetString("EMPLOY_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wage Required.
        /// </summary>
        public static string EMPLOY_WAGE {
            get {
                return ResourceManager.GetString("EMPLOY_WAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string EMPLOY_WAGE_TYPE {
            get {
                return ResourceManager.GetString("EMPLOY_WAGE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly Wage Required.
        /// </summary>
        public static string ENUM_WAGE_HOURLY {
            get {
                return ResourceManager.GetString("ENUM_WAGE_HOURLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Wage Required.
        /// </summary>
        public static string ENUM_WAGE_SALARY {
            get {
                return ResourceManager.GetString("ENUM_WAGE_SALARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ENUM_YESNO_NO {
            get {
                return ResourceManager.GetString("ENUM_YESNO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some.
        /// </summary>
        public static string ENUM_YESNO_SOME {
            get {
                return ResourceManager.GetString("ENUM_YESNO_SOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ENUM_YESNO_YES {
            get {
                return ResourceManager.GetString("ENUM_YESNO_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Required.
        /// </summary>
        public static string PARENT_ADDRESS {
            get {
                return ResourceManager.GetString("PARENT_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Required.
        /// </summary>
        public static string PARENT_FIRSTNAME {
            get {
                return ResourceManager.GetString("PARENT_FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name Required.
        /// </summary>
        public static string PARENT_LASTNAME {
            get {
                return ResourceManager.GetString("PARENT_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name Required.
        /// </summary>
        public static string PARENT_MIDDLENAME {
            get {
                return ResourceManager.GetString("PARENT_MIDDLENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone # Required.
        /// </summary>
        public static string PARENT_PHONENUM {
            get {
                return ResourceManager.GetString("PARENT_PHONENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License # Required.
        /// </summary>
        public static string PERSONAL_DL_NUM {
            get {
                return ResourceManager.GetString("PERSONAL_DL_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Required.
        /// </summary>
        public static string PERSONAL_DL_STATE {
            get {
                return ResourceManager.GetString("PERSONAL_DL_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Required.
        /// </summary>
        public static string PERSONAL_EMAIL {
            get {
                return ResourceManager.GetString("PERSONAL_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Required.
        /// </summary>
        public static string PERSONAL_FIRSTNAME {
            get {
                return ResourceManager.GetString("PERSONAL_FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name Required.
        /// </summary>
        public static string PERSONAL_LASTNAME {
            get {
                return ResourceManager.GetString("PERSONAL_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name Required.
        /// </summary>
        public static string PERSONAL_MIDDLENAME {
            get {
                return ResourceManager.GetString("PERSONAL_MIDDLENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone # Required.
        /// </summary>
        public static string PERSONAL_PHONENUM {
            get {
                return ResourceManager.GetString("PERSONAL_PHONENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSN Required.
        /// </summary>
        public static string PERSONAL_SSN {
            get {
                return ResourceManager.GetString("PERSONAL_SSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Required.
        /// </summary>
        public static string REF_NAME {
            get {
                return ResourceManager.GetString("REF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone # Required.
        /// </summary>
        public static string REF_PHONE {
            get {
                return ResourceManager.GetString("REF_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Required.
        /// </summary>
        public static string REF_RELATION {
            get {
                return ResourceManager.GetString("REF_RELATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Required.
        /// </summary>
        public static string RENTREF_ADDRESS {
            get {
                return ResourceManager.GetString("RENTREF_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string RENTREF_END {
            get {
                return ResourceManager.GetString("RENTREF_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Required.
        /// </summary>
        public static string RENTREF_MOVING_REASON {
            get {
                return ResourceManager.GetString("RENTREF_MOVING_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Required.
        /// </summary>
        public static string RENTREF_NAME {
            get {
                return ResourceManager.GetString("RENTREF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone # Required.
        /// </summary>
        public static string RENTREF_PHONE {
            get {
                return ResourceManager.GetString("RENTREF_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string RENTREF_START {
            get {
                return ResourceManager.GetString("RENTREF_START", resourceCulture);
            }
        }
    }
}
